### ISSUE TITLE
Ticking block entity crash when right clicking flood lights with a wrench

### ISSUE THREAD

**Issue by mskurnik** [Keridos/FloodLights#49]
Right clicking a flood light can cause the client to hard crash and sometimes the server will get corrupted:
>net.minecraft.util.ReportedException: Ticking block entity at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
	at de.keridos.floodlights.tileentity.TileEntityElectricFloodlight.narrowConeSource(TileEntityElectricFloodlight.java:201) ~[TileEntityElectricFloodlight.class:?]
	at de.keridos.floodlights.tileentity.TileEntityElectricFloodlight.addSource(TileEntityElectricFloodlight.java:381) ~[TileEntityElectricFloodlight.class:?]
	at de.keridos.floodlights.tileentity.TileEntityElectricFloodlight.func_145845_h(TileEntityElectricFloodlight.java:350) ~[TileEntityElectricFloodlight.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]

**Comment by Keridos** [comment]
Which build from the Jenkins is that?

**Comment by mskurnik** [comment]
FloodLights-1.7.10-1.0.0-25

**Comment by Keridos** [comment]
Try the latest please, I am fairly sure this is the same crash that already got reported and fixed a few versions ago. https://www.ironhide.de/jenkins/job/FloodLights-dev/

**Comment by mskurnik** [comment]
Yeah.  I just loaded up the corrupted world with the latest dev build and it worked.  Thanks.

**Comment by Keridos** [comment]
Ah ok then the crash was not hard corruption, it was just the floodlight trying the non working thing over and over again.
