### ISSUE TITLE
Game Crashes when inserting RE-BATTERY from buildcraft to FloodLights GUI

### ISSUE THREAD

**Issue by jonylentzmc** [Keridos/FloodLights#98]
Hey!,I'm experiencing crashes when I insert a RE-Battery into any electric light from this mod. This not only crashes the game but also prevent the level from being loaded again until the FloodLight.jar is removed.

**Is there any way that I can disable the GUI from accepting items just as a temporary solution to use this mod in a server without risking having a crash? maybe editing .class file?**

```

Crash.txt:
java.lang.NoClassDefFoundError: cofh/redstoneflux/api/IEnergyContainerItem
	at de.keridos.floodlights.tileentity.TileEntityFLElectric.tryDischargeItem(TileEntityFLElectric.java:93)
	at de.keridos.floodlights.tileentity.TileEntityFLElectric.func_73660_a(TileEntityFLElectric.java:69)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: cofh.redstoneflux.api.IEnergyContainerItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.keridos.floodlights.tileentity.TileEntityFLElectric.tryDischargeItem(TileEntityFLElectric.java:93)
	at de.keridos.floodlights.tileentity.TileEntityFLElectric.func_73660_a(TileEntityFLElectric.java:69)

-- Block entity being ticked --
Details:
	Name: floodlights:electricfloodlight // de.keridos.floodlights.tileentity.TileEntityElectricFloodlight
	Block type: ID #2606 (tile.floodlights:electricFloodlight // de.keridos.floodlights.block.BlockElectricFloodlight // floodlights:electric_floodlight)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-151,66,244), Chunk: (at 9,4,4 in -10,15; contains blocks -160,0,240 to -145,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #2606 (tile.floodlights:electricFloodlight // de.keridos.floodlights.block.BlockElectricFloodlight // floodlights:electric_floodlight)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```

**Comment by jonylentzmc** [comment]
My bad, I guess there's one dependency missing from my mods folder
Just leaving it here in case anyone have the same error in the future
Downloading this fixed the "issue"
https://www.curseforge.com/minecraft/mc-mods/redstone-flux
